# Generated by Django 5.0 on 2023-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
