# Generated by Django 5.0 on 2023-12-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_alter_branches_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='link',
        ),
    ]
