# Generated by Django 5.0 on 2023-12-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0004_material_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banking_app.userprofile'),
        ),
    ]
